### ISSUE TITLE
Additional Libraries are required and not stated

### ISSUE THREAD

**Issue by Tom-Neverwinter** [garymueller/ESP-131GPIO#8]
This will not compile without these two items:

https://github.com/me-no-dev/ESPAsyncTCP

https://github.com/me-no-dev/ESPAsyncUDP

If there is an alternative way of compiling please let me know. 

Successfully compiled 10/4/2021 10:34PM CST

Thank you

**Comment by garymueller** [comment]
Updated the readme to reflect the dependency. Thanks for pointing this out.
