### ISSUE TITLE
(compatability) WeMos d1 mini pro issue

### ISSUE THREAD

**Issue by Tom-Neverwinter** [garymueller/ESP-131GPIO#9]
Sadly when programming the wemos d1 mini pro it seems to hang and never come back up after interacting with it over wifi.

**Comment by garymueller** [comment]
Is there any debug information from the serial monitor that you can provide?  If compiling from older firmware please upgrade to the latest.  There was an issue that was resolved with issue #6 .

**Comment by Tom-Neverwinter** [comment]
I was using the version from one update previous [Sep 18] I didn't realize there was a version released in October. 

esp8266 boards version is 3.0.2

I will flash this tomorrow. [looks like readme update only]

maybe I flashed with the wrong parameters? lolin(wemos) D1 R2 and mini vs d1 mini pro. [to test tomorrow]

I can also connect it to serial and see what it responds with. I dont know how to copy the filesystem off an esp or I could also upload that for diagnostics.

**Comment by garymueller** [comment]
Also note that the file system library was changed over recently from to littlefs (https://github.com/garymueller/ESP-131GPIO/commit/7200295ab9f2921290f3f47455105dca09d7d9eb).  Please make sure that you flash the correct filesystem (not SPIFFS ).

**Comment by Tom-Neverwinter** [comment]
attempted flash: https://pastebin.com/AFM3JNQK

upload littlefs failed. 

however running a littlefs flash subsequently after uploads

I recompiled as it failed to "reset" and instead compiled in debug mode. serial: 1 and debug the minimal: core and wifi as well as the other items. seems fine here.

hmm, changing the WIFI name kills it. serial has stopped responding. [ I was curious if my naming convention was the issue IE Relay bank A vs Relay-bank-A or RELAY-BANK-A etc]

re-flashing after changing the WIFI name restores it. no need to reflash littlefs?


------------------------------------------------------------------------------------------------------------------------------------------
repeating tests on b, then moving to uptime testing. 

------------------------------------------------------------------------------------------------------------------------------------------


and as always thank you for this software, its literally the best!!! ♥

**Comment by garymueller** [comment]
Thankyou for the feedback.  It's unclear to me if you got this running or if there still is an issue.  Are you saying that it was failing when the ssid contained spaces and resolved when spaces were omitted?

**Comment by Tom-Neverwinter** [comment]
no it seems it fails when the ap name is changed. I next need to test and see if its any item that changes causes it to crash. 

stability seems fine inside my house. however the ultimate test as always is outside where it will be running. Which I am also curious if its disconnecting thus trying to change to ap mode and then crashes? 

I will report my findings. 

--------------------------------------------------------------------------------------------------------------------------------------------

I realized its not connecting to my homes wifi, and stays in ap mode. 

Dpuble checked pins for D1 mini pro: 

```
comment out // for proper vector 
//for Wemos D1 R1 pins are 16,5,4,14,12,13,0,2
//vector<int> GpioVector{16,5,4,14,12,13,0,2};
//for WEMOS D1 Mini Pro pins are 16,5,4,14,12,13,0,2
vector<int> GpioVector{16,5,4,14,12,13,0,2};
//for Wemos D1 R2 pins are 16,5,4,0,2,14,12,13
//vector<int> GpioVector{16,5,4,0,2,14,12,13};
```

**Comment by garymueller** [comment]
I'm not sure why its not connecting to your wifi. Does your SSID / password contain special characters and/or spaces?  I'm wondering if its not saving your settings properly.

Thanks for the info on the mini pro pins.  I can add them for others

**Comment by Tom-Neverwinter** [comment]
just seems to be a weird connection issue. I dont have anything special or outside the wifi spec. it also doesn't seem to connect even when on my table line of sight maybe 20ft from my wifi access point. which has 2.4ghz and 5ghz capabilities. 

I'm off today and tomorrow so I will investigate some more after the trees get fixed. [yay late night rj45 fabrication fails XD ] 


----------------------------------------------------------------------------------------------------------------------------------------

so I tested dashes and the ap really doesn't like those.

**Comment by garymueller** [comment]
Can I close this issue? Seems to be resolved as an issue with your network setup
